<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title></title>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="section-header">




</div>


<div id="section-explanatory-data-analysis-on-hr-data" class="section level1">
<h1>Explanatory Data Analysis on HR Data</h1>
<div id="section-preparation" class="section level2">
<h2>Preparation</h2>
<p>We start by loading required libraries for this study.</p>
<pre class="r"><code>library(tidyverse)
library(ggplot2)
library(ggcorrplot)
library(ggthemes)
#substitute(formattable::as.htmlwidget(expr))
library(shiny)
library(formattable)
library(htmlwidgets)
library(ggalt)</code></pre>
</div>
<div id="section-abstract" class="section level2">
<h2>Abstract</h2>
<p>The dataset we have choosen is about human resources. Our aim is to answer an interesting question of a company such as “<em>Why are our best and most experienced employees leaving prematurely?</em>” We will try to find an answer to this question by analyzing answers of the employees to the job satisfaction survey and their work related records. The dataset is formed by the Human Resources (HR) department after conducting a survey on their employees.</p>
</div>
<div id="section-data-description" class="section level2">
<h2>Data Description</h2>
<p>We used <a href="https://www.kaggle.com/ludobenistant/hr-analytics/data">Human Resources Analytics Data</a> from <a href="https://www.kaggle.com">kaggle</a>. This HR data set is obtained from the results of a satisfaction survey the company has carried out on their employees in combination with other HR related records. It consists of 14999 rows and 10 columns. Each row is dedicated for a different employee. Out of 10, 8 columns are in numeric type, while the remaining 2 are in numeric values. Below you can find columns and their explanations, respectively.</p>
<ul>
<li><p><strong>1st Column:</strong> Satisfaction level</p></li>
<li><p><strong>2nd Column:</strong> Last evaluation score</p></li>
<li><p><strong>3rd Column:</strong> Number of projects worked on (yearly basis)</p></li>
<li><p><strong>4th Column:</strong> Average monthly working hours</p></li>
<li><p><strong>5th Column:</strong> Time spent in the company (in years)</p></li>
<li><p><strong>6th Column:</strong> Whether they have had a work accident in the last 2 years</p></li>
<li><p><strong>7th Column:</strong> Whether they have had a promotion in the last 5 years</p></li>
<li><p><strong>8th Column:</strong> Departments</p></li>
<li><p><strong>9th Column:</strong> Salary</p></li>
<li><p><strong>10th Column:</strong> Whether the employee has left</p></li>
</ul>
<p>All the data collected is from last 5 years whereas accident data belongs to past 2 years. This HR database does not take into account the employees that have been fired, transferred or hired in the past year. Our objective is to make predictions about the probabilities that employees may leave their company and what to change to increase their satisfaction levels. We will try to give insights to make best employees more loyal.</p>
</div>
<div id="section-our-tentative-plan-is-as-follows" class="section level2">
<h2>Our tentative plan is as follows:</h2>
<ol style="list-style-type: decimal">
<li>Explore the dimensions of variables</li>
<li>Clean the data if required</li>
<li>Summarise the data and search for correlations wherever possible</li>
<li>Visualize the filtered results</li>
<li>Make conclusions and give insights</li>
</ol>
<div id="section-loading-the-data" class="section level3">
<h3>Loading the Data</h3>
<p>Then we read dataset from csv file and had a quick look at its form.</p>
<pre class="r"><code>d=read.csv(&quot;HR_comma_sep.csv&quot;)
d&lt;- d %&gt;% rename(&quot;departments&quot; = &quot;sales&quot;) %&gt;% tbl_df()
glimpse(d)</code></pre>
<pre><code>## Observations: 14,999
## Variables: 10
## $ satisfaction_level    &lt;dbl&gt; 0.38, 0.80, 0.11, 0.72, 0.37, 0.41, 0.10...
## $ last_evaluation       &lt;dbl&gt; 0.53, 0.86, 0.88, 0.87, 0.52, 0.50, 0.77...
## $ number_project        &lt;int&gt; 2, 5, 7, 5, 2, 2, 6, 5, 5, 2, 2, 6, 4, 2...
## $ average_montly_hours  &lt;int&gt; 157, 262, 272, 223, 159, 153, 247, 259, ...
## $ time_spend_company    &lt;int&gt; 3, 6, 4, 5, 3, 3, 4, 5, 5, 3, 3, 4, 5, 3...
## $ Work_accident         &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...
## $ left                  &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
## $ promotion_last_5years &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...
## $ departments           &lt;fctr&gt; sales, sales, sales, sales, sales, sale...
## $ salary                &lt;fctr&gt; low, medium, medium, low, low, low, low...</code></pre>
<p>As you can see we have 14999 observations for job satisfaction level, latest evaluation (yearly), number of projects worked on, average monthly hours, time spend in the company (in years), work accident (within the past 2 years), promotion within the past 5 years, department and salary. All of them are numeric values except last two columns.</p>
<p>We also checked whether there is any NA or NaN values.</p>
<pre class="r"><code>which(is.na.data.frame(d))</code></pre>
<pre><code>## integer(0)</code></pre>
<p>Since there aren’t any NA/NaN values, no need to omit or complete them. Thus we proceed summarizing the data.</p>
<pre class="r"><code>summary(d)</code></pre>
<pre><code>##  satisfaction_level last_evaluation  number_project  average_montly_hours
##  Min.   :0.0900     Min.   :0.3600   Min.   :2.000   Min.   : 96.0       
##  1st Qu.:0.4400     1st Qu.:0.5600   1st Qu.:3.000   1st Qu.:156.0       
##  Median :0.6400     Median :0.7200   Median :4.000   Median :200.0       
##  Mean   :0.6128     Mean   :0.7161   Mean   :3.803   Mean   :201.1       
##  3rd Qu.:0.8200     3rd Qu.:0.8700   3rd Qu.:5.000   3rd Qu.:245.0       
##  Max.   :1.0000     Max.   :1.0000   Max.   :7.000   Max.   :310.0       
##                                                                          
##  time_spend_company Work_accident         left       
##  Min.   : 2.000     Min.   :0.0000   Min.   :0.0000  
##  1st Qu.: 3.000     1st Qu.:0.0000   1st Qu.:0.0000  
##  Median : 3.000     Median :0.0000   Median :0.0000  
##  Mean   : 3.498     Mean   :0.1446   Mean   :0.2381  
##  3rd Qu.: 4.000     3rd Qu.:0.0000   3rd Qu.:0.0000  
##  Max.   :10.000     Max.   :1.0000   Max.   :1.0000  
##                                                      
##  promotion_last_5years      departments      salary    
##  Min.   :0.00000       sales      :4140   high  :1237  
##  1st Qu.:0.00000       technical  :2720   low   :7316  
##  Median :0.00000       support    :2229   medium:6446  
##  Mean   :0.02127       IT         :1227                
##  3rd Qu.:0.00000       product_mng: 902                
##  Max.   :1.00000       marketing  : 858                
##                        (Other)    :2923</code></pre>
<p>On average, the employees are 64% satisfied with their jobs; they have mean performance score of 0.71 (out of 1); an ordinary employee worked roughly on 3 - 4 different projects per year; it takes them 201.1 hours to complete their jobs per month; an avarage employee worked almost 3.5 years in the company (min = 2, max = 10); attrition rate is 23.81%; unfortunately only 2.1% of employees were promoted in the last 5 years. 8.24% of the employees are highly paid, 48.78% is lowly paid, 42.98% gets medium wage.</p>
<p>We want to see the employees Salary levels :</p>
<pre class="r"><code>d %&gt;% 
  count(salary) %&gt;% 
  formattable(align = &#39;l&#39;)</code></pre>
<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:left;">
salary
</th>
<th style="text-align:left;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
high
</td>
<td style="text-align:left;">
1237
</td>
</tr>
<tr>
<td style="text-align:left;">
low
</td>
<td style="text-align:left;">
7316
</td>
</tr>
<tr>
<td style="text-align:left;">
medium
</td>
<td style="text-align:left;">
6446
</td>
</tr>
</tbody>
</table>
<p>We can see clearly that the range of salaries are not balanced, 8% of high salary while 48 % has low salary.</p>
<p>Below 2 table Inspired from <a href="https://www.kaggle.com/msjgriffiths/explore-explain-density-decision-trees" class="uri">https://www.kaggle.com/msjgriffiths/explore-explain-density-decision-trees</a></p>
<p>let’s see the departments distribution :</p>
<pre class="r"><code>d %&gt;% 
  count(departments) %&gt;% 
  formattable(align = &#39;l&#39;)</code></pre>
<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:left;">
departments
</th>
<th style="text-align:left;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
accounting
</td>
<td style="text-align:left;">
767
</td>
</tr>
<tr>
<td style="text-align:left;">
hr
</td>
<td style="text-align:left;">
739
</td>
</tr>
<tr>
<td style="text-align:left;">
IT
</td>
<td style="text-align:left;">
1227
</td>
</tr>
<tr>
<td style="text-align:left;">
management
</td>
<td style="text-align:left;">
630
</td>
</tr>
<tr>
<td style="text-align:left;">
marketing
</td>
<td style="text-align:left;">
858
</td>
</tr>
<tr>
<td style="text-align:left;">
product_mng
</td>
<td style="text-align:left;">
902
</td>
</tr>
<tr>
<td style="text-align:left;">
RandD
</td>
<td style="text-align:left;">
787
</td>
</tr>
<tr>
<td style="text-align:left;">
sales
</td>
<td style="text-align:left;">
4140
</td>
</tr>
<tr>
<td style="text-align:left;">
support
</td>
<td style="text-align:left;">
2229
</td>
</tr>
<tr>
<td style="text-align:left;">
technical
</td>
<td style="text-align:left;">
2720
</td>
</tr>
</tbody>
</table>
<p>Sales department is the biggest one if we compare with others.</p>
<p>We want to see the salary levels for each department :</p>
<pre class="r"><code>d %&gt;% 
  count(departments, salary) %&gt;% 
  mutate(
    salary = ordered(salary, c(&quot;low&quot;, &quot;medium&quot;, &quot;high&quot;)),
    n = comma(n, 0)
  ) %&gt;% 
  spread(salary, n) %&gt;% 
  formattable(list(area(T, 2:4) ~ color_tile(&quot;grey&quot;, &quot;red&quot;)), align = &#39;l&#39;)</code></pre>
<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:left;">
departments
</th>
<th style="text-align:left;">
low
</th>
<th style="text-align:left;">
medium
</th>
<th style="text-align:left;">
high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
accounting
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c7a1a1">358</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c7a3a3">335</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #bebbbb">74</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
hr
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c7a3a3">335</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c7a0a0">359</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #bebebe">45</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
IT
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #cf8989">609</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #cd9090">535</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #bfbaba">83</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
management
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c2b1b1">180</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c3adad">225</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c3adad">225</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
marketing
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c99c9c">402</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c89f9f">376</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #bfbaba">80</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
product_mng
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #ca9898">451</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c89e9e">383</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #bebbbb">68</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
RandD
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c8a0a0">364</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c89f9f">372</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #bebdbd">51</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
sales
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #ff0000">2099</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #f41e1e">1772</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c5a9a9">269</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
support
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #e05858">1146</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #da6b6b">942</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c1b5b5">141</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
technical
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #e74343">1372</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #e05858">1147</span>
</td>
<td style="text-align:left;">
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #c2afaf">201</span>
</td>
</tr>
</tbody>
</table>
<p>Having known all the column names and their related statistics, we wanted to visualize the distribution of the numerical ones, just to get better understanding for further interpretations. For this reason we employed histogram plots. Notice that bin sizes are adapted with respect to varying ranges of the data.</p>
<pre class="r"><code>p1 &lt;- ggplot(subset(d ), aes(x=satisfaction_level, colour=satisfaction_level)) +
  theme_economist() + 
  scale_color_economist()+
  theme(plot.title = element_text(size=12)) +
  geom_histogram(binwidth = 0.05,color = &#39;black&#39;)+ ##, fill = &#39;#999999&#39;) +
  ggtitle(&quot;Satisfaction Level&quot;) +
  labs(x=&quot;Job Satis. Score&quot;, y=&quot;Employee Count&quot;, size = 8)

p2 &lt;- ggplot(subset(d ), aes(x=last_evaluation, colour=last_evaluation)) +
  theme_economist() + 
  scale_color_economist()+
  theme(plot.title = element_text(size=12)) +
  geom_histogram(binwidth = 0.05,color = &#39;black&#39;)+ ##, fill = &#39;#009E73&#39;) +
  ggtitle(&quot;Last Evaluation&quot;) +
  labs(x=&quot;Performance Score&quot;, y=&quot;Employee Count&quot;, size = 8)

p3 &lt;- ggplot(subset(d ), aes(x=number_project, colour=number_project)) +
  theme_economist() + 
  scale_color_economist()+
  theme(plot.title = element_text(size=12)) +
  geom_histogram(binwidth = 1,color = &#39;black&#39;)+ ##, fill = &#39;#56B4E9&#39;) +
  ggtitle(&quot;Yearly Projects&quot;) +
  labs(x=&quot;Number of Projects&quot;, y=&quot;Employee Count&quot;, size = 8)

p4 &lt;- ggplot(subset(d ), aes(x=average_montly_hours, colour=average_montly_hours)) +
  theme_economist() + 
  scale_color_economist()+
  theme(plot.title = element_text(size=12)) +
  geom_histogram(binwidth = 10,color = &#39;black&#39;)+ ##, fill = &#39;#E69F00&#39;) +
  ggtitle(&quot;Average Monthly Hours&quot;)+
  labs(x=&quot;Monthly Hours&quot;, y=&quot;Employee Count&quot;, size = 8)
  

p5 &lt;- ggplot(subset(d ), aes(x=time_spend_company, colour=time_spend_company)) +
  theme_economist() + 
  scale_color_economist()+
  theme(plot.title = element_text(size=12)) +
  geom_histogram(binwidth = 0.5,color = &#39;black&#39;)+ ##, fill = &#39;#F0E442&#39;) +
  ggtitle(&quot;Time Spent in Company&quot;) +
  labs(x=&quot;Time (Years)&quot;, y=&quot;Employee Count&quot;, size = 8)

p6 &lt;- ggplot(subset(d ), aes(x=Work_accident, colour=Work_accident)) +
  theme_economist() + 
  scale_color_economist()+
  theme(plot.title = element_text(size=12)) +
  geom_bar(color = &#39;black&#39;)+ ##, fill = &#39;#0072B2&#39;) +
  ggtitle(&quot;Work Accidents&quot;) +
  labs(x=&quot;Accident Count&quot;, y=&quot;Employee Count&quot;, size = 8) +
  scale_x_continuous(breaks = c(0,1,1))

p7 &lt;- ggplot(subset(d ), aes(x=left, colour=left)) +
  theme_economist() + 
  scale_color_economist()+
  theme(plot.title = element_text(size=12)) +
  geom_bar(color = &#39;black&#39;)+ ##, fill = &#39;#D55E00&#39;) +
  ggtitle(&quot;Employees Left&quot;) +
  labs(x=&quot;Left Count&quot;, y=&quot;Employee Count&quot;, size = 8) +
  scale_x_continuous(breaks = c(0,1,1))


p8 &lt;- ggplot(subset(d), aes(x=promotion_last_5years, colour=promotion_last_5years)) +
  theme_economist() + 
  scale_color_economist()+
  theme(plot.title = element_text(size=12)) +
  scale_x_continuous(breaks = c(0,1,1)) +
  geom_bar(color = &#39;black&#39;)+ ##, fill = &#39;#CC79A7&#39;) +
  ggtitle(&quot;Promotion in 5 Years&quot;) +
  labs(x=&quot;Promotion Count&quot;, y=&quot;Employee Count&quot;, size = 8) 


multiplot(p1,p2,p3,p4,p5,p6,p7,p8,cols=3)</code></pre>
<p><img src="rmd_6b7ae7d43c7329a783d081de08138a50_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>According to above histograms, we found that; there was nearly no promoted employee in the last five years. Bear in mind that the work accident data belongs to last two years and frequency of accidents is low but not zero. Monthly time spent in the company and number of projects which each employee works on both have positively skewed distributions. So, instead of mean, median value must be considered. Thus, a common employee works 4 projects per year, spending 200 hours per month.</p>
<p>Let’s have a look at departmentwise job satisfaction level of the employees.</p>
<pre class="r"><code> dep_satis &lt;- d %&gt;%
  group_by(departments) %&gt;%
  summarise (Satisfaction =mean(satisfaction_level))
  ggplot(data=dep_satis, aes(x=departments, y=Satisfaction)) +
    theme_economist() + 
      scale_color_economist()+
  theme(axis.text.x = element_text(angle = 90, hjust=0,5))+
  geom_bar(stat=&quot;identity&quot;, position=position_dodge(), fill=&quot;#FF9999&quot;, colour=&quot;black&quot;)</code></pre>
<p><img src="rmd_6b7ae7d43c7329a783d081de08138a50_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>It appears that the level of satisfaction is pretty much the same for all the departments except for some unhappy folks in the accounting department. While rest of the departments average satisfaction value is around 60% (which complies with overall satisfaction rate of 61.28%), accounting department’s mean is below the company’s mean. May be we should focus on that department seperately.</p>
<pre class="r"><code>depLeftSatis &lt;- d %&gt;% group_by(departments) %&gt;% summarise(Total =n(),LeftCount = sum(left), Satisfaction = mean(satisfaction_level) ) %&gt;% mutate(LeftRate = LeftCount/Total) 
                                                         
                

ggplot(data = depLeftSatis, aes( x = reorder(departments, -LeftRate), y = LeftRate, fill = Satisfaction)) +
    theme(axis.text.x = element_text(angle = 60, hjust=1))+
    geom_col()+labs(x= &quot;Departments&quot;, y=&quot;Left Rate&quot;)</code></pre>
<p><img src="rmd_6b7ae7d43c7329a783d081de08138a50_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>As satisfaction level increases, left rate decreases.</p>
<pre class="r"><code>depLeftSatis &lt;- d %&gt;% group_by(departments,salary) %&gt;% summarise(Total =n(),LeftCount = sum(left), Satisfaction = mean(satisfaction_level) ) %&gt;% mutate(LeftRate = LeftCount/Total)

ggplot(data = depLeftSatis, aes( x = reorder(departments, -LeftRate), y = LeftRate, fill=salary)) +
    theme(axis.text.x = element_text(angle = 60, hjust=1)) +
    geom_bar(stat=&quot;identity&quot;,position = &quot;stack&quot;)+labs(x= &quot;Departments&quot;, y=&quot;Left Rate&quot;)</code></pre>
<p><img src="rmd_6b7ae7d43c7329a783d081de08138a50_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Notice that altough job satisfaction level is uniformly distributed among the departments, the left rate varies abrubtly, maximized at the HR department. So there must be other factors that effect employee’s decision to sign-out, such as salary.</p>
<p>Now, let’s look at the categorical variables, salary and department name. We wanted to compare left and remained employee counts by departments and salary categories. When salary category does not give much insight about the characteristics of left people, we found that the 3 departments have considerably higher number of people left. These departments are sales, technical and support.</p>
<pre class="r"><code># install.packages(&quot;ggthemes&quot;) # Install 
library(ggthemes) # Load

p9 &lt;- ggplot(d, aes(x=d$departments,fill=as.character(d$left)))+
      theme_economist() + 
      scale_color_economist()+
      theme(axis.text.x = element_text(angle = 90, hjust=0))+
      geom_bar() +
      labs(x=&quot;Departments&quot;, y=&quot;Employee Count&quot;, fill=&quot;Left or Not&quot;)

p10 &lt;- ggplot(d, aes(x=d$salary,fill=as.character(d$left) ))+
       theme_economist() + 
       scale_color_economist()+
       theme(axis.text.x = element_text(angle = 90, hjust=0))+
       geom_bar() +
       labs(x=&quot;Salary&quot;, y =&quot;Employee Count&quot;,fill=&quot;Left or Not&quot;)

multiplot(p9,p10,cols=2)</code></pre>
<p><img src="rmd_6b7ae7d43c7329a783d081de08138a50_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Let’s see correlation matrix for whole company</p>
<pre class="r"><code>CorrMat &lt;- round(cor(d[,0:8]),3)
ggcorrplot(CorrMat, hc.order = TRUE, 
           #type = &quot;lower&quot;, 
           lab = TRUE, 
           lab_size = 3, 
           method=&quot;circle&quot;, 
           colors = c(&quot;tomato2&quot;, &quot;white&quot;, &quot;springgreen3&quot;), 
           title=&quot;Correlogram of Numeric Values&quot;, 
           ggtheme=theme_bw)</code></pre>
<p><img src="rmd_6b7ae7d43c7329a783d081de08138a50_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Maybe it is better to focus on the people who quit, already. We look at the correlation matrix of those to understand factors affecting their final decision to quit.</p>
<pre class="r"><code>dLeft &lt;- d %&gt;% filter(left==1) %&gt;% select(-left)


 summary(dLeft)</code></pre>
<pre><code>##  satisfaction_level last_evaluation  number_project  average_montly_hours
##  Min.   :0.0900     Min.   :0.4500   Min.   :2.000   Min.   :126.0       
##  1st Qu.:0.1300     1st Qu.:0.5200   1st Qu.:2.000   1st Qu.:146.0       
##  Median :0.4100     Median :0.7900   Median :4.000   Median :224.0       
##  Mean   :0.4401     Mean   :0.7181   Mean   :3.856   Mean   :207.4       
##  3rd Qu.:0.7300     3rd Qu.:0.9000   3rd Qu.:6.000   3rd Qu.:262.0       
##  Max.   :0.9200     Max.   :1.0000   Max.   :7.000   Max.   :310.0       
##                                                                          
##  time_spend_company Work_accident     promotion_last_5years
##  Min.   :2.000      Min.   :0.00000   Min.   :0.000000     
##  1st Qu.:3.000      1st Qu.:0.00000   1st Qu.:0.000000     
##  Median :4.000      Median :0.00000   Median :0.000000     
##  Mean   :3.877      Mean   :0.04733   Mean   :0.005321     
##  3rd Qu.:5.000      3rd Qu.:0.00000   3rd Qu.:0.000000     
##  Max.   :6.000      Max.   :1.00000   Max.   :1.000000     
##                                                            
##      departments      salary    
##  sales     :1014   high  :  82  
##  technical : 697   low   :2172  
##  support   : 555   medium:1317  
##  IT        : 273                
##  hr        : 215                
##  accounting: 204                
##  (Other)   : 613</code></pre>
<p>We pairwise plotted job satisfaction level versus average montly hours and also satisfaction level versus time spent in the company. Meanwhile, we also highlighted employees left the company.</p>
<pre class="r"><code>#Define three main groups which left the company 
d$left &lt;- factor(d$left, labels=c(&quot;No&quot;, &quot;Yes&quot;))

gg &lt;- ggplot(d,aes(satisfaction_level,average_montly_hours))

gg &lt;- gg +geom_point(aes(col=factor(d$left)))

gg + geom_encircle(data=subset(d, 
                               satisfaction_level&gt;=0.05 &amp; 
                                 satisfaction_level&lt;0.12 &amp; 
                                 average_montly_hours&gt;240 &amp; 
                                 average_montly_hours&lt;=310), colour=&quot;blue&quot;,expand=0.05,spread=0.02,size=2) +
  geom_encircle(data=subset(d, 
                               satisfaction_level&gt;=0.35 &amp; 
                                 satisfaction_level&lt;0.47 &amp; 
                                 average_montly_hours&gt;122 &amp; 
                                 average_montly_hours&lt;164), colour=&quot;blue&quot;, expand=0,spread=0.02,size=2) +
    geom_encircle(data=subset(d, 
                               satisfaction_level&gt;=0.47 &amp; 
                                 satisfaction_level&lt;=1 &amp; 
                                 average_montly_hours&gt;129 &amp; 
                                 average_montly_hours&lt;279), colour=&quot;green&quot;, expand=0, spread=0.02,size=2) +
      geom_encircle(data=subset(d, 
                               satisfaction_level&gt;=0.715 &amp; 
                                 satisfaction_level&lt;=0.9 &amp; 
                                 average_montly_hours&gt;215 &amp; 
                                 average_montly_hours&lt;278), colour=&quot;blue&quot;, expand=0, spread=0.02,size=2) +

   scale_x_continuous(breaks=seq(0.08, 1, 0.08), limits = c(0.08, 1)) + 
  scale_y_continuous(breaks=seq(100, 315, 30), limits = c(100, 315)) +
  labs(x=&quot;Satisfaction Level&quot;,y=&quot;Avg. Monthly Hours&quot;, title=&quot;Satisfaction Level vs. Average Monthly Hours&quot;,col=&quot;Left Work&quot;) </code></pre>
<pre><code>## Warning: Removed 54 rows containing missing values (geom_point).</code></pre>
<p><img src="rmd_6b7ae7d43c7329a783d081de08138a50_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>From the satisfaction vs. monthly hours plot, three seperate clusters are clearly seen with following properties:</p>
<ul>
<li><em>Group 1:</em> Low satisfaction level and long working hours</li>
<li><em>Group 2:</em> Mediocre satisfaction level and low working hours</li>
<li><em>Group 3:</em> High satisfaction level and high working hours</li>
</ul>
<p>It is no surprise that employees belonging to the first group quits the job. Furthermore, it would not be wrong to call the second group as <strong>unmotivated</strong> and the last group as <strong>motivated</strong>. It is very surprising to see motivated employees with such a high satisfaction level (&gt;0.8) and long working hours. Those ones also must be the ones who works on more projects than the average, since average monthly hours highly correlates with number of projects.</p>
<pre class="r"><code>gg &lt;- ggplot(d,aes(satisfaction_level,time_spend_company))

gg &lt;- gg +geom_point(aes(col=factor(d$left)))

gg + geom_encircle(data=subset(d, 
                               satisfaction_level&gt;=0.72 &amp; 
                                 satisfaction_level&lt;=0.92 &amp; 
                                 time_spend_company&gt;4 &amp; 
                                 time_spend_company&lt;6.02), colour=&quot;blue&quot;, expand=0.02,spread=0.02,size=2)+
  geom_encircle(data=subset(d, 
                               satisfaction_level&gt;=0.36 &amp; 
                                 satisfaction_level&lt;=0.47 &amp; 
                                 time_spend_company==3 ), colour=&quot;blue&quot;, expand=0.02,spread=0.02,size=2)+
    geom_encircle(data=subset(d, 
                               satisfaction_level&gt;=0.08 &amp; 
                                 satisfaction_level&lt;=0.12 &amp; 
                                 time_spend_company&gt;=3 &amp;
                                time_spend_company&lt;=5), colour=&quot;blue&quot;, expand=0.02,spread=0.02,size=2)+

   scale_x_continuous(breaks=seq(0.08, 1, 0.08), limits = c(0.08, 1)) + 
  scale_y_continuous(breaks =  seq(0,10,by=2), limits = c(0,10))+
  labs(x=&quot;Satisfaction Level&quot;,y=&quot;Time Spend In Company (Years)&quot;, title=&quot;Satisfaction Level vs. Time Spend In Company (Years)&quot;,col=&quot;Left Work&quot;) </code></pre>
<p><img src="rmd_6b7ae7d43c7329a783d081de08138a50_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>From the graph above, it is seen that the motivated last group leaves the company between four and six years. May be they did not the promotion or salary increase they expected. People who passes six years thereshold, does not tend to leave the company later.</p>
<!-- ## K-Means Clustering -->
<!-- ```{r} -->
<!-- #Get selected columns from data set -->
<!-- d2 <- d %>% select(satisfaction_level,average_montly_hours) -->
<!-- set.seed(35) -->
<!-- #apply k-means clustering -->
<!-- clusters<-kmeans(d2,centers=4) -->
<!-- #Get the clusters -->
<!-- mds_clusters<-data.frame(genre=names(genre_cluster$cluster),cluster_mds=genre_cluster$cluster) %>% arrange(cluster_mds,genre) -->
<!-- mds_clusters -->
<!-- ``` -->
<pre class="r"><code># install.packages(&quot;scatterplot3d&quot;) # Install
# library(&quot;scatterplot3d&quot;) # load
# 
# scatterplot3d(x=d$satisfaction_level, y=d$average_montly_hours, z=d$departments,)
# 
# 
# 
#  devtools::install_github(&quot;ropensci/plotly&quot;)
# 
# # install.packages(&quot;assertthat&quot;)
# 
# library(plotly)
# gr &lt;- d %&gt;% select(satisfaction_level,average_montly_hours,departments,left) %&gt;% group_by(departments,average_montly_hours,satisfaction_level) %&gt;% 
#   summarise(Total =n(),
#   LeftCount = sum(as.integer(left==&quot;Yes&quot;))) %&gt;%    
#   mutate(LeftRate = LeftCount/Total)
#   
# 
# 
# # print(gr$LeftCount)
# 
# colors &lt;- c(&#39;#4AC6B7&#39;, &#39;#1972A4&#39;, &#39;#965F8A&#39;, &#39;#FF7070&#39;, &#39;#C61951&#39;)
# 
# p &lt;- plotly(gr, x = ~gr$Satisfaction, y = ~gr$average_montly_hours, z = ~gr$LeftRate, color = ~d$departments, size = ~gr$departments, colors = colors,
#              marker = list(symbol = &#39;circle&#39;, sizemode = &#39;diameter&#39;), sizes = c(5, 150)) %&gt;%
#   layout(title = &#39;Life Expectancy v. Per Capita GDP, 2007&#39;,
#          scene = list(xaxis = list(title = &#39;GDP per capita (2000 dollars)&#39;,
#                       gridcolor = &#39;rgb(255, 255, 255)&#39;,
#                       # range = c(2.003297660701705, 5.191505530708712),
#                       type = &#39;log&#39;,
#                       zerolinewidth = 1,
#                       ticklen = 5,
#                       gridwidth = 2),
#                yaxis = list(title = &#39;Life Expectancy (years)&#39;,
#                       gridcolor = &#39;rgb(255, 255, 255)&#39;,
#                       # range = c(36.12621671352166, 91.72921793264332),
#                       zerolinewidth = 1,
#                       ticklen = 5,
#                       gridwith = 2),
#                zaxis = list(title = &#39;Population&#39;,
#                             gridcolor = &#39;rgb(255, 255, 255)&#39;,
#                             type = &#39;log&#39;,
#                             zerolinewidth = 1,
#                             ticklen = 5,
#                             gridwith = 2)),
#          paper_bgcolor = &#39;rgb(243, 243, 243)&#39;,
#          plot_bgcolor = &#39;rgb(243, 243, 243)&#39;)</code></pre>
<pre class="r"><code>CorrMat &lt;- round(cor(dLeft[,0:7]),3)
ggcorrplot(CorrMat, hc.order = TRUE, 
           #type = &quot;lower&quot;, 
           lab = TRUE, 
           lab_size = 3, 
           method=&quot;circle&quot;, 
           colors = c(&quot;tomato2&quot;, &quot;white&quot;, &quot;springgreen3&quot;), 
           title=&quot;Correlogram of Numeric Values&quot;, 
           ggtheme=theme_bw)</code></pre>
<p><img src="rmd_6b7ae7d43c7329a783d081de08138a50_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Correlogram created from numerical values in our dataset shows that Average Monthly Hours is highly correlated with Number Of Projects as expected. The ones who works on more than avarage (3) projects, should spend more time in the company. And also last evaluation score correlates highly with number of projects and average monthly hours. High evaluation score is given to people who works on more projects by spending more time in the company.</p>
</div>
</div>
<div id="section-principal-component-analysis" class="section level2">
<h2>Principal Component Analysis</h2>
<p>Now, we are going to use this correlation matrix to make principal component analysis. Before that we need to transform salaries to numeric values to see their effect on left rate.</p>
<pre class="r"><code>names(dLeft)</code></pre>
<pre><code>## [1] &quot;satisfaction_level&quot;    &quot;last_evaluation&quot;       &quot;number_project&quot;       
## [4] &quot;average_montly_hours&quot;  &quot;time_spend_company&quot;    &quot;Work_accident&quot;        
## [7] &quot;promotion_last_5years&quot; &quot;departments&quot;           &quot;salary&quot;</code></pre>
<pre class="r"><code>dLeft_pca &lt;- dLeft  %&gt;% mutate(salary_Num = ifelse(salary == &quot;low&quot;, 0, ifelse(salary == &quot;medium&quot;, 1, 2))) %&gt;% select(-salary,-departments)

pca_wo_scaling &lt;-princomp(as.matrix(dLeft_pca[,1:8]),cor=FALSE)

pca_w_scaling&lt;-princomp(as.matrix(dLeft_pca[,1:8]),cor=TRUE)

summary(pca_wo_scaling,loadings=TRUE)</code></pre>
<pre><code>## Importance of components:
##                            Comp.1       Comp.2       Comp.3       Comp.4
## Standard deviation     61.2186054 0.8855625966 0.7550824369 5.371824e-01
## Proportion of Variance  0.9995393 0.0002091566 0.0001520624 7.696204e-05
## Cumulative Proportion   0.9995393 0.9997484474 0.9999005097 9.999775e-01
##                              Comp.5       Comp.6       Comp.7       Comp.8
## Standard deviation     2.123482e-01 1.663285e-01 8.061656e-02 7.219703e-02
## Proportion of Variance 1.202625e-05 7.378471e-06 1.733331e-06 1.390182e-06
## Cumulative Proportion  9.999895e-01 9.999969e-01 9.999986e-01 1.000000e+00
## 
## Loadings:
##                       Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6 Comp.7
## satisfaction_level                   0.263                0.937 -0.207
## last_evaluation                                           0.203  0.960
## number_project               -0.989                                   
## average_montly_hours   1.000                                          
## time_spend_company           -0.111  0.957               -0.265       
## Work_accident                                     -1.000              
## promotion_last_5years                                           -0.177
## salary_Num                                  1.000                     
##                       Comp.8
## satisfaction_level          
## last_evaluation       -0.169
## number_project              
## average_montly_hours        
## time_spend_company          
## Work_accident               
## promotion_last_5years -0.984
## salary_Num</code></pre>
<pre class="r"><code>summary(pca_w_scaling,loadings=TRUE)</code></pre>
<pre><code>## Importance of components:
##                           Comp.1    Comp.2    Comp.3    Comp.4    Comp.5
## Standard deviation     1.8162209 1.1428322 1.0272619 1.0030200 0.9672535
## Proportion of Variance 0.4123323 0.1632582 0.1319084 0.1257561 0.1169474
## Cumulative Proportion  0.4123323 0.5755905 0.7074989 0.8332550 0.9502024
##                            Comp.6     Comp.7     Comp.8
## Standard deviation     0.41439073 0.36124911 0.31009692
## Proportion of Variance 0.02146496 0.01631261 0.01202001
## Cumulative Proportion  0.97166737 0.98797999 1.00000000
## 
## Loadings:
##                       Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6 Comp.7
## satisfaction_level            0.852                       0.352 -0.147
## last_evaluation       -0.522                              0.433  0.584
## number_project        -0.493 -0.317                              0.199
## average_montly_hours  -0.510 -0.194                       0.253 -0.773
## time_spend_company    -0.468  0.359                      -0.790       
## Work_accident                        0.686  0.326 -0.649              
## promotion_last_5years                0.712 -0.129  0.689              
## salary_Num                          -0.140  0.936  0.320              
##                       Comp.8
## satisfaction_level     0.350
## last_evaluation       -0.442
## number_project         0.784
## average_montly_hours  -0.199
## time_spend_company    -0.166
## Work_accident               
## promotion_last_5years       
## salary_Num</code></pre>
<pre class="r"><code># pr.without.scaling &lt;- prcomp(as.matrix(dLeft_pca[,1:8],center=TRUE,scale=FALSE))
# 
biplot(pca_wo_scaling)</code></pre>
<pre><code>## Warning in arrows(0, 0, y[, 1L] * 0.8, y[, 2L] * 0.8, col = col[2L], length
## = arrow.len): zero-length arrow is of indeterminate angle and so skipped

## Warning in arrows(0, 0, y[, 1L] * 0.8, y[, 2L] * 0.8, col = col[2L], length
## = arrow.len): zero-length arrow is of indeterminate angle and so skipped

## Warning in arrows(0, 0, y[, 1L] * 0.8, y[, 2L] * 0.8, col = col[2L], length
## = arrow.len): zero-length arrow is of indeterminate angle and so skipped</code></pre>
<p><img src="rmd_6b7ae7d43c7329a783d081de08138a50_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<pre class="r"><code># 
# 
# pr.with.scaling &lt;- prcomp(as.matrix(dLeft_pca[,1:8],center=TRUE,scale=TRUE))
# 
biplot(pca_w_scaling)</code></pre>
<p><img src="rmd_6b7ae7d43c7329a783d081de08138a50_files/figure-html/unnamed-chunk-22-2.png" width="672" /></p>
<p>Cumulative variance plot is as below:</p>
<pre class="r"><code>ggplot(data.frame(pc=1:5,cum_var=c(0.9996162, 0.9998254162, 0.9999774670, 0.9999894955,9.999969e-01)),aes(x=pc,y=cum_var)) + 
  geom_point() +
  geom_line() +
  labs(x=&quot;Principal Component Number&quot;,
       y=&quot;Cumulative Proportion&quot;, 
       title=&quot;Principal Component vs. Cumulative Proportion&quot;)</code></pre>
<p><img src="rmd_6b7ae7d43c7329a783d081de08138a50_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>The first component explains %99 of the variance and it is exactly average mounthly hours! We are also surprised with this result as you are. We were expecting to see salary too as a negative factor effecting attirition rate. We are going build our prediction model just on this factor to see future run away employees.</p>
</div>
<div id="section-k-means-clustering" class="section level2">
<h2>K-Means Clustering</h2>
<p>We tried K-Means clustering to be able to group mass of people who left the company.</p>
<pre class="r"><code>#Filter to get the data from left people only
dleft&lt;- subset(d, left==&#39;Yes&#39;) 
dleft&lt;- select(dleft,-left)


#apply k-means with 4 clusters and 20 iterations
set.seed(20)
dleft_Cluster &lt;- kmeans(dleft[, 1:7], 4, nstart = 20)

dleft_Cluster</code></pre>
<pre><code>## K-means clustering with 4 clusters of sizes 501, 850, 583, 1637
## 
## Cluster means:
##   satisfaction_level last_evaluation number_project average_montly_hours
## 1          0.1320758       0.8550100       6.091816             293.6587
## 2          0.4877176       0.8826588       5.194118             261.0682
## 3          0.7020240       0.8912693       4.737564             231.4648
## 4          0.4163592       0.5291081       2.161881             144.6054
##   time_spend_company Work_accident promotion_last_5years
## 1           4.099800    0.03792415           0.005988024
## 2           4.608235    0.04117647           0.001176471
## 3           4.878216    0.06346484           0.000000000
## 4           3.071472    0.04764814           0.009163103
## 
## Clustering vector:
##    [1] 4 2 2 3 4 4 2 2 3 4 4 1 3 4 4 4 4 2 4 2 1 4 1 4 4 3 3 4 4 4 1 4 4 4
##   [35] 3 2 4 4 1 4 2 4 4 1 2 4 4 2 4 4 4 4 4 4 1 4 2 1 4 3 3 1 3 4 1 4 4 2
##   [69] 3 4 2 2 4 1 2 1 1 4 4 4 4 4 4 2 1 1 3 4 4 1 4 3 4 4 2 4 2 1 1 3 4 4
##  [103] 4 2 4 3 2 4 4 4 4 1 4 2 3 4 2 2 4 4 4 4 3 1 4 2 4 4 2 4 1 4 3 4 4 4
##  [137] 1 4 2 2 3 4 2 4 2 4 3 1 2 4 1 4 4 4 4 1 3 1 4 4 1 3 4 3 2 1 4 4 4 4
##  [171] 2 4 1 1 2 4 4 4 4 1 4 2 2 1 4 4 1 4 4 4 1 3 3 2 2 1 1 1 1 3 2 4 3 2
##  [205] 2 4 3 3 4 4 4 1 3 4 4 4 4 3 4 3 1 4 4 2 4 2 4 4 3 3 4 2 3 4 2 2 4 4
##  [239] 4 2 1 4 4 4 2 4 4 4 3 1 2 2 3 2 2 4 2 4 3 1 4 2 4 2 4 2 1 4 4 4 4 2
##  [273] 2 1 2 3 2 3 2 3 2 1 2 1 4 4 1 1 3 4 4 3 4 1 2 4 4 4 4 2 4 1 2 4 2 4
##  [307] 4 1 4 1 1 1 4 4 2 3 4 4 2 4 4 3 2 1 4 4 4 2 2 4 4 1 2 4 1 4 2 4 4 3
##  [341] 1 4 3 4 4 1 2 1 2 4 1 3 2 4 3 4 4 4 4 2 1 2 4 2 4 3 2 4 3 2 4 4 4 4
##  [375] 2 2 1 4 3 3 4 4 4 4 4 2 1 2 4 4 2 4 2 1 4 4 4 1 2 2 2 3 2 3 3 2 3 2
##  [409] 3 3 3 2 4 4 3 4 3 2 3 3 2 1 2 4 4 4 2 4 4 4 3 4 4 2 1 4 2 4 3 4 4 4
##  [443] 3 3 4 1 4 1 4 3 3 2 1 4 2 4 3 2 4 4 4 4 2 2 3 4 4 1 3 4 2 4 2 4 3 4
##  [477] 2 2 3 2 4 2 3 4 4 4 4 3 2 3 1 4 3 1 3 2 3 2 4 4 2 4 1 4 3 1 2 4 4 4
##  [511] 4 4 2 1 2 3 2 1 4 4 2 3 1 3 3 4 4 1 1 4 4 4 3 4 3 4 1 4 2 3 4 2 3 3
##  [545] 4 3 4 4 2 4 1 2 2 2 4 1 4 4 4 1 1 4 4 1 4 1 1 1 4 3 4 2 3 4 4 4 3 2
##  [579] 3 4 4 3 3 4 4 4 4 3 2 4 4 2 2 4 2 2 3 2 4 1 2 3 2 3 1 2 4 2 4 1 2 4
##  [613] 4 3 1 2 4 2 4 4 2 2 2 4 4 2 4 4 3 4 1 4 2 4 3 4 4 4 3 4 4 3 3 4 3 4
##  [647] 2 4 4 4 4 2 1 4 1 3 3 4 4 3 4 4 2 2 2 2 3 2 2 4 3 2 4 4 4 4 2 3 4 3
##  [681] 2 4 1 4 3 3 2 2 2 3 4 3 2 1 2 3 1 1 4 4 4 3 4 4 3 4 3 2 2 4 2 4 2 3
##  [715] 4 4 4 3 3 2 4 4 4 4 4 4 4 4 4 1 4 3 3 4 2 2 3 4 2 2 1 4 4 1 4 3 4 4
##  [749] 4 3 4 4 4 4 2 4 3 4 4 4 1 2 4 4 3 3 3 4 1 4 1 1 4 4 4 4 2 1 2 2 2 3
##  [783] 3 4 4 2 3 4 3 3 3 1 2 2 1 4 4 1 2 4 2 4 2 1 2 3 4 3 1 1 3 1 4 4 2 3
##  [817] 2 2 4 4 1 3 4 4 4 1 2 4 4 4 3 2 4 3 2 1 4 1 3 4 4 1 2 4 4 4 2 3 1 1
##  [851] 4 4 3 4 2 4 2 1 2 2 3 4 4 4 2 3 4 4 2 4 4 2 2 3 1 2 2 2 4 2 4 2 1 4
##  [885] 4 2 4 4 1 1 4 3 2 2 2 1 4 1 2 3 2 4 4 4 4 3 1 1 2 2 2 4 2 4 2 3 1 4
##  [919] 2 2 4 4 4 4 4 3 3 3 2 3 2 4 4 2 1 4 1 1 3 4 3 4 1 3 2 2 4 4 3 1 1 4
##  [953] 1 1 4 2 4 4 4 1 4 2 4 4 4 4 1 2 4 4 4 2 1 4 1 4 1 1 4 2 4 4 2 4 2 4
##  [987] 4 2 2 4 3 3 4 2 4 4 4 3 4 4 2 2 4 4 2 2 4 4 2 3 4 4 1 2 4 4 4 3 4 3
## [1021] 2 4 4 4 4 4 4 1 2 2 1 1 3 4 2 2 4 2 3 2 1 2 3 2 4 4 2 4 4 3 3 2 4 3
## [1055] 2 1 4 4 3 1 4 4 2 1 4 4 4 4 3 3 3 2 3 4 2 2 2 3 4 2 3 2 3 2 3 2 2 2
## [1089] 2 4 4 4 3 2 2 1 4 4 4 4 2 2 4 4 2 4 4 2 1 2 2 4 2 1 1 4 2 2 3 4 1 4
## [1123] 4 1 4 4 3 2 2 1 4 4 4 3 4 1 2 2 1 4 3 4 3 1 4 4 3 2 4 2 4 3 4 1 4 1
## [1157] 4 4 3 2 2 1 1 3 1 1 4 4 3 4 2 1 4 2 1 1 4 2 3 4 3 4 3 2 4 4 2 1 1 4
## [1191] 2 2 4 3 3 2 4 3 1 4 2 2 4 2 4 1 4 3 1 3 2 3 2 4 1 3 4 2 4 3 4 3 4 3
## [1225] 1 4 4 4 1 4 4 2 2 4 4 4 4 3 2 4 4 4 1 2 1 1 4 2 4 1 3 4 4 3 4 4 4 3
## [1259] 3 4 2 4 2 4 2 1 4 4 4 4 4 1 4 3 4 1 4 2 4 2 4 2 3 4 2 4 4 2 1 4 4 2
## [1293] 4 3 4 4 4 4 4 2 1 4 1 4 3 3 2 4 2 3 2 4 2 3 4 2 2 4 2 4 1 4 2 4 2 4
## [1327] 2 4 1 2 4 1 2 2 4 1 4 4 4 3 2 2 4 4 4 4 3 1 4 3 3 2 2 3 2 3 2 4 2 4
## [1361] 2 2 4 4 4 1 4 4 4 1 2 4 2 4 2 4 3 2 3 4 2 3 2 4 1 4 2 4 3 4 3 4 4 3
## [1395] 4 4 1 4 4 1 4 2 3 3 2 4 2 3 4 3 2 1 4 2 4 4 1 1 1 3 4 3 2 4 4 1 4 4
## [1429] 2 2 4 4 2 4 4 4 4 4 1 2 2 2 4 1 4 2 4 2 4 4 2 2 2 3 4 4 4 2 4 4 4 4
## [1463] 4 4 1 4 2 2 2 1 4 4 4 3 3 4 3 4 4 4 2 2 1 2 4 2 2 4 1 4 4 4 4 4 4 2
## [1497] 2 4 4 4 2 4 2 4 3 4 4 4 2 4 3 4 4 2 4 2 4 4 2 4 4 4 2 4 2 2 2 4 4 4
## [1531] 2 4 3 4 1 4 2 4 4 3 4 3 4 3 2 1 2 2 2 2 1 4 2 3 2 2 4 4 1 3 1 1 4 4
## [1565] 4 2 2 4 4 4 4 3 4 1 4 2 2 4 1 4 3 2 2 2 4 3 3 1 2 1 4 4 4 1 4 4 1 3
## [1599] 2 4 1 3 4 4 3 4 4 3 1 2 2 1 4 4 4 1 4 3 2 4 4 3 2 4 3 2 2 4 4 2 1 1
## [1633] 4 4 4 4 4 2 4 4 3 4 2 1 3 1 2 4 1 4 3 3 2 1 2 2 2 3 3 2 4 4 2 4 2 4
## [1667] 4 4 3 4 4 4 3 3 2 2 2 4 2 4 2 2 4 4 4 3 1 4 4 4 3 4 4 4 2 2 4 1 1 4
## [1701] 4 1 4 3 4 2 4 4 2 2 2 4 4 4 4 4 1 1 4 2 2 3 2 1 3 2 4 2 4 2 4 4 2 4
## [1735] 2 4 3 2 2 2 4 4 2 4 4 2 2 4 3 3 2 3 2 3 4 4 2 4 4 2 4 1 3 3 4 3 4 2
## [1769] 4 4 2 3 2 2 4 2 2 4 4 4 3 4 2 4 4 2 4 4 4 4 4 3 4 4 4 3 3 4 2 4 2 2
## [1803] 2 4 4 2 4 1 4 2 4 4 4 2 2 1 4 4 2 1 4 1 4 1 4 2 2 1 2 2 4 4 2 2 1 4
## [1837] 2 2 1 4 1 3 4 4 4 4 4 2 2 4 4 4 4 4 4 3 1 2 4 4 3 2 2 3 4 4 4 4 4 2
## [1871] 2 2 2 1 4 2 1 4 4 4 2 4 1 4 3 1 1 4 3 1 3 4 4 1 2 3 4 2 4 4 3 4 2 2
## [1905] 1 4 4 3 3 2 1 3 4 4 1 4 4 4 4 2 4 3 4 4 2 3 4 2 1 4 3 4 4 4 3 4 1 4
## [1939] 4 1 4 2 4 1 3 4 4 2 4 2 2 3 4 4 3 2 4 1 4 4 4 1 4 1 2 2 2 4 3 4 4 4
## [1973] 4 4 4 4 4 4 4 2 1 3 2 4 4 1 3 3 3 2 4 4 3 4 4 4 1 4 2 4 4 2 2 3 4 4
## [2007] 2 2 3 4 4 1 3 4 4 4 4 2 4 2 1 4 1 4 4 3 3 4 4 4 1 4 4 4 3 2 4 4 1 4
## [2041] 2 4 4 1 2 4 4 2 4 4 4 4 4 4 1 4 2 1 4 3 3 1 3 4 1 4 4 2 3 4 2 2 4 1
## [2075] 2 1 1 4 4 4 4 4 4 2 1 1 3 4 4 1 4 3 4 4 2 4 2 1 1 3 4 4 4 2 4 3 2 4
## [2109] 4 4 4 1 4 2 3 4 2 2 4 4 4 4 3 1 4 2 4 4 2 4 1 4 3 4 4 4 1 4 2 2 3 4
## [2143] 2 4 2 4 3 1 2 4 1 4 4 4 4 1 3 1 4 4 1 3 4 3 2 1 4 4 4 4 2 4 1 1 2 4
## [2177] 4 4 4 1 4 2 2 1 4 4 1 4 4 4 1 3 3 2 2 1 1 1 1 3 2 4 3 2 2 4 3 3 4 4
## [2211] 4 1 3 4 4 4 4 3 4 3 1 4 4 2 4 2 4 4 3 3 4 2 3 4 2 2 4 4 4 2 1 4 4 4
## [2245] 2 4 4 4 3 1 2 2 3 2 2 4 2 4 3 1 4 2 4 2 4 2 1 4 4 4 4 2 2 1 2 3 2 3
## [2279] 2 3 2 1 2 1 4 4 1 1 3 4 4 3 4 1 2 4 4 4 4 2 4 1 2 4 2 4 4 1 4 1 1 1
## [2313] 4 4 2 3 4 4 2 4 4 3 2 1 4 4 4 2 2 4 4 1 2 4 1 4 2 4 4 3 1 4 3 4 4 1
## [2347] 2 1 2 4 1 3 2 4 3 4 4 4 4 2 1 2 4 2 4 3 2 4 3 2 4 4 4 4 2 2 1 4 3 3
## [2381] 4 4 4 4 4 2 1 2 4 4 2 4 2 1 4 4 4 1 2 2 2 3 2 3 3 2 3 2 3 3 3 2 4 4
## [2415] 3 4 3 2 3 3 2 1 2 4 4 4 2 4 4 4 3 4 4 2 1 4 2 4 3 4 4 4 3 3 4 1 4 1
## [2449] 4 3 3 2 1 4 2 4 3 2 4 4 4 4 2 2 3 4 4 1 3 4 2 4 2 4 3 4 2 2 3 2 4 2
## [2483] 3 4 4 4 4 3 2 3 1 4 3 1 3 2 3 2 4 4 2 4 1 4 3 1 2 4 4 4 4 4 2 1 2 3
## [2517] 2 1 4 4 2 3 1 3 3 4 4 1 1 4 4 4 3 4 3 4 1 4 2 3 4 2 3 3 4 3 4 4 2 4
## [2551] 1 2 2 2 4 1 4 4 4 1 1 4 4 1 4 1 1 1 4 3 4 2 3 4 4 4 3 2 3 4 4 3 3 4
## [2585] 4 4 4 3 2 4 4 2 2 4 2 2 3 2 4 1 2 3 2 3 1 2 4 2 4 1 2 4 4 3 1 2 4 2
## [2619] 4 4 2 2 2 4 4 2 4 4 3 4 1 4 2 4 3 4 4 4 3 4 4 3 3 4 3 4 2 4 4 4 4 2
## [2653] 1 4 1 3 3 4 4 3 4 4 2 2 2 2 3 2 2 4 3 2 4 4 4 4 2 3 4 3 2 4 1 4 3 3
## [2687] 2 2 2 3 4 3 2 1 2 3 1 1 4 4 4 3 4 4 3 4 3 2 2 4 2 4 2 3 4 4 4 3 3 2
## [2721] 4 4 4 4 4 4 4 4 4 1 4 3 3 4 2 2 3 4 2 2 1 4 4 1 4 3 4 4 4 3 4 4 4 4
## [2755] 2 4 3 4 4 4 1 2 4 4 3 3 3 4 1 4 1 1 4 4 4 4 2 1 2 2 2 3 3 4 2 2 3 4
## [2789] 4 2 2 3 4 4 1 3 4 4 4 4 2 4 2 1 4 1 4 4 3 3 4 4 4 1 4 4 4 3 2 4 4 1
## [2823] 4 2 4 4 1 2 4 4 2 4 4 4 4 4 4 1 4 2 1 4 3 3 1 3 4 1 4 4 2 3 4 2 2 4
## [2857] 1 2 1 1 4 4 4 4 4 4 2 1 1 3 4 4 1 4 3 4 4 2 4 2 1 1 3 4 4 4 2 4 3 2
## [2891] 4 4 4 4 1 4 2 3 4 2 2 4 4 4 4 3 1 4 2 4 4 2 4 1 4 3 4 4 4 1 4 2 2 3
## [2925] 4 2 4 2 4 3 1 2 4 1 4 4 4 4 1 3 1 4 4 1 3 4 3 2 1 4 4 4 4 2 4 1 1 2
## [2959] 4 4 4 4 1 4 2 2 1 4 4 1 4 4 4 1 3 3 2 2 1 1 1 1 3 2 4 3 2 2 4 3 3 4
## [2993] 4 4 1 3 4 4 4 4 3 4 3 1 4 4 2 4 2 4 4 3 3 4 2 3 4 2 2 4 4 4 2 1 4 4
## [3027] 4 2 4 4 4 3 1 2 2 3 2 2 4 2 4 3 1 4 2 4 2 4 2 1 4 4 4 4 2 2 1 2 3 2
## [3061] 3 2 3 2 1 2 1 4 4 1 1 3 4 4 3 4 1 2 4 4 4 4 2 4 1 2 4 2 4 4 1 4 1 1
## [3095] 1 4 4 2 3 4 4 2 4 4 3 2 1 4 4 4 2 2 4 4 1 2 4 1 4 2 4 4 3 1 4 3 4 4
## [3129] 1 2 1 2 4 1 3 2 4 3 4 4 4 4 2 1 2 4 2 4 3 2 4 3 2 4 4 4 4 2 2 1 4 3
## [3163] 3 4 4 4 4 4 2 1 2 4 4 2 4 2 1 4 4 4 1 2 2 2 3 2 3 3 2 3 2 3 3 3 2 4
## [3197] 4 3 4 3 2 3 3 2 1 2 4 4 4 2 4 4 4 3 4 4 2 1 4 2 4 3 4 4 4 3 3 4 1 4
## [3231] 1 4 3 3 2 1 4 2 4 3 2 4 4 4 4 2 2 3 4 4 1 3 4 2 4 2 4 3 4 2 2 3 2 4
## [3265] 2 3 4 4 4 4 3 2 3 1 4 3 1 3 2 3 2 4 4 2 4 1 4 3 1 2 4 4 4 4 4 2 1 2
## [3299] 3 2 1 4 4 2 3 1 3 3 4 4 1 1 4 4 4 3 4 3 4 1 4 2 3 4 2 3 3 4 3 4 4 2
## [3333] 4 1 2 2 2 4 1 4 4 4 1 1 4 4 1 4 1 1 1 4 3 4 2 3 4 4 4 3 2 3 4 4 3 3
## [3367] 4 4 4 4 3 2 4 4 2 2 4 2 2 3 2 4 1 2 3 2 3 1 2 4 2 4 1 2 4 4 3 1 2 4
## [3401] 2 4 4 2 2 2 4 4 2 4 4 3 4 1 4 2 4 3 4 4 4 3 4 4 3 3 4 3 4 2 4 4 4 4
## [3435] 2 1 4 1 3 3 4 4 3 4 4 2 1 4 1 3 4 4 4 4 4 2 2 4 4 4 4 4 4 3 1 2 4 4
## [3469] 3 2 2 3 4 4 4 4 4 2 2 2 2 1 4 2 1 4 4 4 2 4 1 4 3 1 1 4 3 1 3 4 4 1
## [3503] 2 3 4 2 4 4 3 4 2 2 1 4 4 3 3 2 1 3 4 4 1 4 4 4 4 2 4 3 4 4 2 3 4 2
## [3537] 1 4 3 4 4 4 3 4 1 4 4 1 4 2 4 1 3 4 4 2 4 2 2 3 4 4 3 2 4 1 4 4 4 1
## [3571] 4
## 
## Within cluster sum of squares by cluster:
## [1]  49859.94  63442.51  87533.13 207356.50
##  (between_SS / total_SS =  97.0 %)
## 
## Available components:
## 
## [1] &quot;cluster&quot;      &quot;centers&quot;      &quot;totss&quot;        &quot;withinss&quot;    
## [5] &quot;tot.withinss&quot; &quot;betweenss&quot;    &quot;size&quot;         &quot;iter&quot;        
## [9] &quot;ifault&quot;</code></pre>
<p>When we compare the values of 4 clusters with our previously defined groups in two graphs (Satisfaction Level vs. Avg. Monthly Hours, Satisfaction Level vs. Time Spend In Company), we found that there are similarities below:</p>
<ul>
<li>Cluster 1 corresponds with Group 1 (Low satisfaction level (0.08 - 0.12) and long working hours (&gt;240 hours))</li>
<li>Cluster 4 corresponds with Group 2 (Mediocre satisfaction level (0.36 - 0.45) and low working hours (120 - 160 hours))</li>
</ul>
<p>As there are not enough samples in Group 3, basic k-means clustering we applied was not successful enough to discriminate the third Group (High satisfaction level and relatively high working hours). We think that further filtering is needed before reapplying clustering methods to this data.</p>
<p><div class="shiny-input-panel">
<div class="shiny-flow-layout">
<div>
<div class="form-group shiny-input-container">
<label class="control-label" for="dept">Department:</label>
<div>
<select id="dept"><option value="accounting">accounting</option>
<option value="hr">hr</option>
<option value="IT">IT</option>
<option value="management">management</option>
<option value="marketing">marketing</option>
<option value="product_mng">product_mng</option>
<option value="RandD">RandD</option>
<option value="sales" selected>sales</option>
<option value="support">support</option>
<option value="technical">technical</option></select>
<script type="application/json" data-for="dept" data-nonempty="">{}</script>
</div>
</div>
</div>
<div>
<div class="form-group shiny-input-container">
<label class="control-label" for="salary">Salary:</label>
<div>
<select id="salary"><option value="low" selected>low</option>
<option value="medium">medium</option>
<option value="high">high</option></select>
<script type="application/json" data-for="salary" data-nonempty="">{}</script>
</div>
</div>
</div>
<div>
<div class="form-group shiny-input-container">
<label class="control-label" for="stlvl">Satisfaction level:</label>
<input class="js-range-slider" id="stlvl" data-type="double" data-min="0.05" data-max="1" data-from="0.05" data-to="1" data-step="0.05" data-grid="true" data-grid-num="9.5" data-grid-snap="false" data-prettify-separator="," data-prettify-enabled="true" data-keyboard="true" data-keyboard-step="5.26315789473684" data-drag-interval="true" data-data-type="number"/>
</div>
</div>
</div>
</div><div id="out318c7ed221fce990" class="shiny-plot-output" style="width: 100% ; height: 400px"></div></p>
</div>
<div id="section-references" class="section level2">
<h2>References</h2>
<p><a href="https://www.kaggle.com/ludobenistant/hr-analytics/data">Human Resources Analytics Data Set</a></p>
<p><a href="https://www.kaggle.com/msjgriffiths/explore-explain-density-decision-trees">Explore &amp; Explain: Density &amp; Decision Trees</a></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
